# Generated by Django 5.1.7 on 2025-04-14 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0004_librovisto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='librofavorito',
            unique_together={('usuario', 'titulo', 'autor')},
        ),
        migrations.AlterUniqueTogether(
            name='librovisto',
            unique_together={('usuario', 'titulo', 'autor')},
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_ISBN', models.CharField(max_length=13)),
                ('texto', models.TextField()),
                ('calificacion', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'libro_ISBN')},
            },
        ),
    ]
