# Generated by Django 5.1.7 on 2025-04-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0009_alter_libro_isbn_alter_libro_id_delete_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='ISBN',
        ),
        migrations.AddField(
            model_name='libro',
            name='google_books_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
