# Generated by Django 5.1.7 on 2025-04-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0010_remove_libro_isbn_libro_google_books_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='google_books_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
