# Generated by Django 5.2 on 2025-04-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0012_comentarioexterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='Autor desconocido', max_length=200),
        ),
    ]
