# Generated by Django 5.1.7 on 2025-04-24 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0014_alter_libro_autor_librousuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='creado_por_usuario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion_usuario',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='slug_autor',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='libro',
            name='slug_titulo',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='libro',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LibroUsuario',
        ),
    ]
